// <auto-generated />
namespace WPF_Schoolbib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Library : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Library));
        
        string IMigrationMetadata.Id
        {
            get { return "202101241014596_Library"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
